grub2/btrfs: Add ability to boot from subvolumes
This patch adds the ability to specify a different root on a btrfs
filesystem too boot from other than the default one.

btrfs-list-snapshots <dev> will list the subvolumes available on the
filesystem.

set btrfs_subvol=<path> and set btrfs_subvolid=<subvolid> will specify
which subvolume to use and any pathnames provided with either of those
variables set will start using that root. If the subvolume or subvolume id
doesn't exist, then an error case will result.

It is possible to boot into a separate GRUB instance by exporting the
variable and loading the config file from the subvolume.

Signed-off-by: Jeff Mahoney <jeffm@suse.com>

squash! grub2/btrfs: Add ability to boot from subvolumes

V1:
  * Use overflow checking primitives where the arithmetic expression for
    buffer allocations may include unvalidated data

V2:
Fix gcc12 build error:
[   48s] ../grub-core/fs/btrfs.c: In function 'grub_cmd_btrfs_info':
[   48s] ../grub-core/fs/btrfs.c:2495:7: error: the comparison will always evaluate as 'true' for the address of 'label' will never be NULL [-Werror=address]
[   48s]  2495 |   if (data->sblock.label)
[   48s]       |       ^~~~
[   48s] ../grub-core/fs/btrfs.c:89:8: note: 'label' declared here
[   48s]    89 |   char label[0x100];
[   48s]       |        ^~~~~