ieee1275/powerpc: enables device mapper discovery
this patch enables the device mapper discovery on ofpath.c. Currently,
when we are dealing with a device like /dev/dm-* the ofpath returns null
since there is no function implemented to handle this case.

This patch implements a function that will look into /sys/block/dm-*
devices and search recursively inside slaves directory to find the root
disk.

V2:
Fix gcc12 build error:
[   48s] ../grub-core/osdep/linux/ofpath.c: In function 'get_slave_from_dm':
[   48s] ../grub-core/osdep/linux/ofpath.c:803:7: error: pointer 'device_path' may be used after 'free' [-Werror=use-after-free]
[   48s]   803 |       grub_util_warn (_("cannot open directory `%s'"), device_path);
[   48s]       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   48s] ../grub-core/osdep/linux/ofpath.c:777:5: note: call to 'free' here
[   48s]   777 |     free(device_path);
[   48s]       |     ^~~~~~~~~~~~~~~~~